export { Welcome } from './Welcome/WelcomeDefault';
export { Welcome as WelcomeOld } from './Welcome/WelcomeOld';
export { WelcomeRedesign } from './Welcome/WelcomeRedesign';
export { WelcomeRd1 } from './Welcome/WelcomeRd1';
export { WelcomeRd2 } from './Welcome/WelcomeRd2';
export { WelcomeRd3 } from './Welcome/WelcomeRd3';
export { SeoInfo } from './SeoInfo';
export { SeoInfoDefault } from './SeoInfoDefault';
export { HowItWorks } from './HowItWorks';
export { HowItWorksRedesign } from './HowItWorksRedesign';
export { HowItWorksRd2 } from './HowItWorksRd2';
export { DrawResult } from './DrawResult';
export { HowDoIt } from './HowDoIt';
export { HowDoItRedesign } from './HowDoItRedesign';
export { Faq } from './Faq/FaqDefault';
export { Faq as FaqOld } from './Faq/FaqOld';
export { GetAppInfo } from './GetAppInfo';
export { NotDifficult } from './NotDifficult';
export { Contacts } from './Contacts';
export { RepaymentInfo } from './RepaymentInfo';
export { Information } from './Information';
export { Explanations } from './Explanations';
export { CovidMessage } from './CovidMessage';
export { VendorStores } from './VendorStores';
