export { StaticApi } from './StaticApi';
export { CommonApi } from './CommonApi';
export { TrackingApi } from './TrackingApi';
export { LoanApi } from './LoanApi';
export { UserApi } from './UserApi';
export { OtpApi } from './OtpApi';
export { LoyaltyApi } from './LoyaltyApi';
export { PageApi } from './PageApi';
export { RepaymentApi } from './RepaymentApi';
